source 'https://github.com/JakyHao/PPSpecs.git'
source 'hppts://github.com/CocoaPods/Specs.git'

use_frameworks!

platform :ios, '8.0'

target 'PPNoteKit_Tests' do
  pod 'PPNoteKit', :path => '../'

  
end
